DROP DATABASE IF EXISTS checkOutData;
CREATE DATABASE checkOutData;
USE checkOutData;

CREATE TABLE checkOutData(
  id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  address1 VARCHAR(255) NOT NULL,
  address2 VARCHAR(255),
  city VARCHAR(255) NOT NULL,
  state VARCHAR(255) NOT NULL,
  zip INT(255) NOT NULL,
  phone INT(10) NOT NULL,
  creditCard INT(255) NOT NULL, 
  expDate INT(4) NOT NULL,
  CVV INT(3) NOT NULL,
  billingZip INT(255) NOT NULL
);

